version: '3.1'

services:
    sync_data:
        image: data_sync:1.0
        volumes:
            - 'sync_data:/volume'
            - 'C:\Users\Alexa\Documents\ssh:/host'
volumes:
  sync_data:
      external: true