version: '3.1'

services:
    sonarqube:
        image: sonarqube:7.9.1-community
        environment:
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
            - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonarqube
        ports:
            - "9000:9000"
            - "9092:9092"
        volumes:
            - sonar_conf:/opt/sonarqube/conf
            - sonar_data:/opt/sonarqube/data
            - sonar_extensions:/opt/sonarqube/extensions
    postgres:
        image: postgres:10.1
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
            - POSTGRES_DB=sonarqube
        volumes:
            - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
        external: true
  sonar_data:
       external: true
  sonar_conf:
      external: true
  sonar_extensions:
      external: true