version: '3.1'

services:
    intellij:
        image: intellijjdk11:2019.2
        environment:
            - DISPLAY=192.168.10.1:0.0
        volumes:
            - 'C:\Users\Alexa\Documents\Docker Directories\Intellij\config:/root/.IntelliJIdea2019.2'
            - 'C:\Users\Alexa\Documents\Docker Directories\Intellij\m2:/root/.m2'
            - 'c:\Users\Alexa\Documents\Java projects:/root/Intellij'
            - 'C:\Users\Alexa\Documents\Docker Directories\Intellij\user:/root/.java/.userPrefs'
            - 'c:\Users\Alexa\Documents\Docker Directories\tomcat\webapps:/usr/local/src'
    mysql:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: password123
        volumes:
            - 'C:\Users\Alexa\Documents\Docker Directories\mysql:/var/lib/mysql'
    tomcat:
        image: tomcat:9-jdk13-openjdk-oracle
        volumes:
            - 'c:\Users\Alexa\Documents\Docker Directories\tomcat\webapps\root.war:/usr/local/tomcat/webapps/root.war'
        ports:
            - 8080:8080